#ifndef FORMGENWIDGETS_GLOBAL_H
#define FORMGENWIDGETS_GLOBAL_H

#define FORMGENWIDGETS_QT_VERSION_MAJOR ${FORMGENWIDGETS_QT_VERSION_MAJOR}
#define FORMGENWIDGETS_QT_VERSION_MINOR ${FORMGENWIDGETS_QT_VERSION_MINOR}
#define FORMGENWIDGETS_QT_VERSION_PATCH ${FORMGENWIDGETS_QT_VERSION_PATCH}

#include <QtCore/QtGlobal>

#if ${FORMGENWIDGETS_STATIC}
 // static lib
 #define FORMGENWIDGETS_EXPORT
#elif defined(FORMGENWIDGETS_LIBRARY)
 #define FORMGENWIDGETS_EXPORT Q_DECL_EXPORT
#else
 #define FORMGENWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // FORMGENWIDGETS_GLOBAL_H
